# Generated by Django 4.2.7 on 2023-12-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('dificultad', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes_publicacion')),
            ],
        ),
    ]
